import pandas as pd, numpy as np, seaborn as sns
from matplotlib import rcParams
import matplotlib
matplotlib.rcParams['font.size'] = 20
matplotlib.rcParams['font.family']='serif'
import matplotlib.pyplot as plt
plt.switch_backend('agg')
def get_lowest_scoring_rmsd(score,rmsd): # Gets the lowest scoring Model's RMSD
        return rmsd[score.index(min(score))]
#Rosetta_Sc,IM_Sc,Decoy_RMSD,Decoy_TMsc
#1YTQ_HM_OLD_WEIGHTS_ALL_1.0_ccsnoise_0.0_with_rescore.csv
protein_data= pd.read_csv('./FIG6/1YTQ_HM_OLD_WEIGHTS_ALL_1.0_ccsnoise_0.0_with_rescore.csv',header=0)
rmsd = protein_data['Decoy_RMSD']
tmscore = protein_data['Decoy_TMsc']
rs_score   = protein_data['Rosetta_Sc']
im_score   = protein_data['IM_Sc']
rs_min_score = min(rs_score)
im_min_score = min(im_score)
rs_min_score_rmsd = get_lowest_scoring_rmsd(list(rs_score),list(rmsd))
rs_min_score_tmsc = get_lowest_scoring_rmsd(list(rs_score),list(tmscore))
im_min_score_rmsd = get_lowest_scoring_rmsd(list(im_score),list(rmsd))
im_min_score_tmsc = get_lowest_scoring_rmsd(list(im_score),list(tmscore))
plt.figure()
plt.scatter(rmsd,rs_score,s=50,alpha=0.25,color='powderblue')
plt.scatter(rmsd,im_score,s=50,alpha=0.25,color='mediumpurple')
plt.scatter(rs_min_score_rmsd,rs_min_score,s=350,alpha=0.85,color='powderblue',marker='*',edgecolor='black')
plt.scatter(im_min_score_rmsd,im_min_score,s=350,alpha=0.85,color='mediumpurple',marker='*',edgecolor='black')
plt.ylim(-770,300)
plt.xticks()
plt.yticks()
plt.xlabel(r"RMSD ($\AA$)",fontsize=10)
plt.ylabel(r"Score",fontsize=10)
plt.tight_layout()
plt.savefig('./FIG6/a_i_1ytq.png',dpi=1200)
plt.close()
plt.figure()
plt.scatter(tmscore,rs_score,s=50,alpha=0.25,color='powderblue')
plt.scatter(tmscore,im_score,s=50,alpha=0.25,color='mediumpurple')
plt.scatter(rs_min_score_tmsc,rs_min_score,s=350,alpha=0.85,color='powderblue',marker='*',edgecolor='black')
plt.scatter(im_min_score_tmsc,im_min_score,s=350,alpha=0.85,color='mediumpurple',marker='*',edgecolor='black')
plt.ylim(-770,300)
plt.xticks()
plt.yticks()
plt.xlabel(r"TM-Score",fontsize=10)
plt.ylabel(r"Score",fontsize=10)
plt.tight_layout()
plt.savefig('./FIG6/a_ii_1ytq.png',dpi=1200)
plt.close()
#1QOY_HM_OLD_WEIGHTS_ALL_1.0_ccsnoise_0.0_with_rescore.csv
protein_data= pd.read_csv('./FIG6/1QOY_HM_OLD_WEIGHTS_ALL_1.0_ccsnoise_0.0_with_rescore.csv',header=0)
rmsd = protein_data['Decoy_RMSD']
tmscore = protein_data['Decoy_TMsc']
rs_score   = protein_data['Rosetta_Sc']
im_score   = protein_data['IM_Sc']
rs_min_score = min(rs_score)
im_min_score = min(im_score)
rs_min_score_rmsd = get_lowest_scoring_rmsd(list(rs_score),list(rmsd))
rs_min_score_tmsc = get_lowest_scoring_rmsd(list(rs_score),list(tmscore))
im_min_score_rmsd = get_lowest_scoring_rmsd(list(im_score),list(rmsd))
im_min_score_tmsc = get_lowest_scoring_rmsd(list(im_score),list(tmscore))
plt.figure()
plt.scatter(rmsd,rs_score,s=50,alpha=0.25,color='powderblue')
plt.scatter(rmsd,im_score,s=50,alpha=0.25,color='mediumpurple')
plt.scatter(rs_min_score_rmsd,rs_min_score,s=350,alpha=0.85,color='powderblue',marker='*',edgecolor='black')
plt.scatter(im_min_score_rmsd,im_min_score,s=350,alpha=0.85,color='mediumpurple',marker='*',edgecolor='black')
plt.ylim(-1150,-500)
plt.xticks()
plt.yticks()
plt.xlabel(r"RMSD ($\AA$)",fontsize=10)
plt.ylabel(r"Score",fontsize=10)
plt.tight_layout()
plt.savefig('./FIG6/a_i_1qoy.png',dpi=1200)
plt.close()
plt.figure()
plt.scatter(tmscore,rs_score,s=50,alpha=0.25,color='powderblue')
plt.scatter(tmscore,im_score,s=50,alpha=0.25,color='mediumpurple')
plt.scatter(rs_min_score_tmsc,rs_min_score,s=350,alpha=0.85,color='powderblue',marker='*',edgecolor='black')
plt.scatter(im_min_score_tmsc,im_min_score,s=350,alpha=0.85,color='mediumpurple',marker='*',edgecolor='black')
plt.ylim(-1150,-500)
plt.xticks()
plt.yticks()
plt.xlabel(r"TM-Score",fontsize=10)
plt.ylabel(r"Score",fontsize=10)
plt.tight_layout()
plt.savefig('./FIG6/a_ii_1qoy.png',dpi=1200)
plt.close()
#1VXG_EX_OLD_WEIGHTS_ALL_1.0_ccsnoise_0.0_with_rescore.csv
protein_data= pd.read_csv('./FIG6/1VXG_EX_OLD_WEIGHTS_ALL_1.0_ccsnoise_0.0_with_rescore.csv',header=0)
rmsd = protein_data['Decoy_RMSD']
tmscore = protein_data['Decoy_TMsc']
rs_score   = protein_data['Rosetta_Sc']
im_score   = protein_data['IM_Sc']
rs_min_score = min(rs_score)
im_min_score = min(im_score)
rs_min_score_rmsd = get_lowest_scoring_rmsd(list(rs_score),list(rmsd))
rs_min_score_tmsc = get_lowest_scoring_rmsd(list(rs_score),list(tmscore))
im_min_score_rmsd = get_lowest_scoring_rmsd(list(im_score),list(rmsd))
im_min_score_tmsc = get_lowest_scoring_rmsd(list(im_score),list(tmscore))
plt.figure()
plt.scatter(rmsd,rs_score,s=50,alpha=0.25,color='powderblue')
plt.scatter(rmsd,im_score,s=50,alpha=0.25,color='mediumpurple')
plt.scatter(rs_min_score_rmsd,rs_min_score,s=350,alpha=0.85,color='powderblue',marker='*',edgecolor='black')
plt.scatter(im_min_score_rmsd,im_min_score,s=350,alpha=0.85,color='mediumpurple',marker='*',edgecolor='black')
plt.ylim(-425,-150)
plt.xticks()
plt.yticks()
plt.xlabel(r"RMSD ($\AA$)",fontsize=10)
plt.ylabel(r"Score",fontsize=10)
plt.tight_layout()
plt.savefig('./FIG6/a_i_1vxg.png',dpi=1200)
plt.close()
plt.figure()
plt.scatter(tmscore,rs_score,s=50,alpha=0.25,color='powderblue')
plt.scatter(tmscore,im_score,s=50,alpha=0.25,color='mediumpurple')
plt.scatter(rs_min_score_tmsc,rs_min_score,s=350,alpha=0.85,color='powderblue',marker='*',edgecolor='black')
plt.scatter(im_min_score_tmsc,im_min_score,s=350,alpha=0.85,color='mediumpurple',marker='*',edgecolor='black')
plt.ylim(-425,-150)
plt.xticks()
plt.yticks()
plt.xlabel(r"TM-Score",fontsize=10)
plt.ylabel(r"Score",fontsize=10)
plt.tight_layout()
plt.savefig('./FIG6/a_ii_1vxg.png',dpi=1200)
plt.close()
#2MLT_EX_OLD_WEIGHTS_ALL_1.0_ccsnoise_0.0_with_rescore.csv
protein_data= pd.read_csv('./FIG6/2MLT_EX_OLD_WEIGHTS_ALL_1.0_ccsnoise_0.0_with_rescore.csv',header=0)
rmsd = protein_data['Decoy_RMSD']
tmscore = protein_data['Decoy_TMsc']
rs_score   = protein_data['Rosetta_Sc']
im_score   = protein_data['IM_Sc']
rs_min_score = min(rs_score)
im_min_score = min(im_score)
rs_min_score_rmsd = get_lowest_scoring_rmsd(list(rs_score),list(rmsd))
rs_min_score_tmsc = get_lowest_scoring_rmsd(list(rs_score),list(tmscore))
im_min_score_rmsd = get_lowest_scoring_rmsd(list(im_score),list(rmsd))
im_min_score_tmsc = get_lowest_scoring_rmsd(list(im_score),list(tmscore))
plt.figure()
plt.scatter(rmsd,rs_score,s=50,alpha=0.25,color='powderblue')
plt.scatter(rmsd,im_score,s=50,alpha=0.25,color='mediumpurple')
plt.scatter(rs_min_score_rmsd,rs_min_score,s=350,alpha=0.85,color='powderblue',marker='*',edgecolor='black')
plt.scatter(im_min_score_rmsd,im_min_score,s=350,alpha=0.85,color='mediumpurple',marker='*',edgecolor='black')
plt.ylim(-65,80)
plt.xticks()
plt.yticks()
plt.xlabel(r"RMSD ($\AA$)",fontsize=10)
plt.ylabel(r"Score",fontsize=10)
plt.tight_layout()
plt.savefig('./FIG6/a_i_2mlt.png',dpi=1200)
plt.close()
plt.figure()
plt.scatter(tmscore,rs_score,s=50,alpha=0.25,color='powderblue')
plt.scatter(tmscore,im_score,s=50,alpha=0.25,color='mediumpurple')
plt.scatter(rs_min_score_tmsc,rs_min_score,s=350,alpha=0.85,color='powderblue',marker='*',edgecolor='black')
plt.scatter(im_min_score_tmsc,im_min_score,s=350,alpha=0.85,color='mediumpurple',marker='*',edgecolor='black')
plt.ylim(-65,80)
plt.xticks()
plt.yticks()
plt.xlabel(r"TM-Score",fontsize=10)
plt.ylabel(r"Score",fontsize=10)
plt.tight_layout()
plt.savefig('./FIG6/a_ii_2mlt.png',dpi=1200)
plt.close()
conv = pd.read_csv('./exp_rmsd_tmscore_for_violins', sep='\s+', header=0)
plt.figure()
ax= sns.violinplot(x="METHOD",y="RMSD",data=conv,split=True,cut=0,inner="box")#
ax.set(xlabel='')
ax.set(ylabel='')
plt.ylabel(r"RMSD ($\AA$)",fontsize=10)
plt.tight_layout()
plt.savefig('./FIG6/b_i.png',dpi=1200)
plt.close()
plt.figure()
ax= sns.violinplot(x="METHOD",y="TMSCORE",data=conv,split=True,cut=0,inner="box")#
ax.set(xlabel='')
ax.set(ylabel='')
plt.ylabel(r"TM-Score",fontsize=10)
plt.tight_layout()
plt.savefig('./FIG6/b_ii.png',dpi=1200)
plt.close()